version: '3.9'

services:
  currency-converter-challenge:
    container_name: 'currency-converter'
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    volumes:
      - ./:/app
    restart: always
